version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 20
    commands:
      - echo "Installing dependencies..."
      # - npm install
      - echo "Installing SonarQube scanner..."
      - npm install -g sonarqube-scanner # Install the SonarQube scanner globally
      - echo "SonarQube scanner installed."
      
  pre_build:
    commands:
      - echo "Running pre-build steps..."   

  build:
    commands:
      - echo "Packaging Lambda function..."
      - zip -r whales_secured.zip .
      - echo "Running SonarQube analysis..."
      - sonar-scanner \
          -Dsonar.projectKey=whales_secured \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://zaomrtfv005.omlams.net:9900  \
          -Dsonar.login=8934107be5c8c0dba9f9b1779b9f6cc267f78f15 #

  post_build:
    commands:
      - echo "Deploying to AWS Lambda..."
      - aws lambda update-function-code --function-name whales_secured --zip-file fileb://whales_secured.zip
      - echo "Deployment completed."
      
# artifacts:
#   type: zip
#   files:
#     - whales_secured.zip 
#     - outputtemplate.yaml



